# Settings for the app
app:
  # HTML Title
  title: Cockburn
  # Header name
  name: Cockburn
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to give input on geogrpahic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: false
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: -32.125080
      lng: 115.832950
    zoom: 14
    minZoom: 13
    maxZoom: 18
    maxBounds: [ [-32.242732, 115.638222], [-31.859740, 116.106069] ]
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/aisey.p9n38ib0/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: http://{s}.tiles.mapbox.com/v3/aisey.p9n38ib0/{z}/{x}/{y}.png
      layer_control:
        type: baselayer
        name: 'Streets'
      display: true   
    - url: http://{s}.tiles.mapbox.com/v3/aisey.pgm7ci1e/{z}/{x}/{y}.png
      layer_control:
        type: baselayer
        name: 'Satellite'
      display: false   
    - url: http://{s}.tiles.mapbox.com/v3/aisey.Cockburn_bikelanes/{z}/{x}/{y}.png
      layer_control:
        type: overlay
        name: 'Bike Lanes'
      display: false  
    - url: http://{s}.tiles.mapbox.com/v3/aisey.Cockburn_bikeparking/{z}/{x}/{y}.png
      layer_control:
        type: overlay
        name: 'Bike Parking'
      display: false  
    - url: http://{s}.tiles.mapbox.com/v3/aisey.Cockburn_amenities/{z}/{x}/{y}.png
      layer_control:
        type: overlay
        name: 'Drinking'
      display: false  
      
# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  bikeidea:
    index: 0
    label: _(Bike Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "bikeidea" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FDCB14'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "bikeidea" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-yellow-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "bikeidea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  walkidea:
    index: 1
    label: _(Walk Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "walkidea" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FDCB14'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "walkidea" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-yellow-walk.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "walkidea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]        
  bikelike:
    index: 2
    label: _(Bike Like Spot)
    rules:
      - condition: '"{{location_type}}" === "bikelike" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#45BA00'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "bikelike" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "bikelike" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  walklike:
    index: 3
    label: _(Walk Like Spot)
    rules:
      - condition: '"{{location_type}}" === "walklike" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#45BA00'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "walklike" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-walk.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "walklike" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]        
  bike:
    index: 4
    label: _(Bike Issue Spot)
    rules:
      - condition: '"{{location_type}}" === "bike" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "bike" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-red-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "bike" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  walk:
    index: 5
    label: _(Walk Issue Spot)
    rules:
      - condition: '"{{location_type}}" === "walk" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "walk" && {{map.zoom}} >= 14 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-red-walk.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "walk" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]                                         
                          
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(What do you think about riding or walking in the City of Cockburn?)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street, Intersection, Park, Landmark, etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Bike Idea)
          value: bikeidea 
        - label: _(Walking Idea)
          value: walkidea
        - label: _(Bike Like)
          value: bikelike 
        - label: _(Walking Like)
          value: walklike      
        - label: _(Bike Issue)
          value: bike
        - label: _(Walking Issue)
          value: walk        
      name: location_type
      attrs:
        - key: required
    - prompt: _(Please tell us more about your idea at this spot?)
      type: textarea
      name: description_idea
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe the idea at this spot...)
    - prompt: _(Please tell us more about what you like at this spot?)
      type: textarea
      name: description_like
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe what you like at this spot...)            
    - prompt: _(What is the issue at this walking spot?)
      type: select
      options: 
        - label: _(Choose One)
          value: ''
        - label: _(Poorly maintained footpaths)
          value: Poorly maintained footpaths
        - label: _(No crossing facilities)
          value: No crossing facilities
        - label: _(Limited time to cross at signal)
          value: Limited time to cross at signal 
        - label: _(Unattractive walking route)
          value: Unattractive walking route   
        - label: _(Limited or no wayfinding signage)
          value: Limited or no wayfinding signage  
        - label: _(Poor lighting)
          value: Poor Lighting  
        - label: _(Limited or no footpaths)
          value: Limited or no footpaths
        - label: _(Limited or no disability access)
          value: Limited or no disability access
        - label: _(Limited shelter)
          value: Limited shelter
        - label: _(Limited seating)
          value: Limited seating  
        - label: _(Other)
          value: Other             
      name: walk_issue
      optional: true
    - prompt: _(What is the issue at this bike spot?)
      type: select
      options: 
        - label: _(Choose One)
          value: ''
        - label: _(No bicycle lanes)
          value: No bicycle lanes
        - label: _(Unsafe bicycle lanes)
          value: Unsafe bicycle lanes 
        - label: _(Bicycle lane ends unexpectedly)
          value: Bicycle lane ends unexpectedly  
        - label: _(Lack of wayfinding or signage)
          value: Lack of wayfinding or signage  
        - label: _(Bicycle lane blocked)
          value: Bicycle lane blocked
        - label: _(High risk of car dooring)
          value: High risk of car dooring)
        - label: _(Limited or no bicycle parking)
          value: Limited or no bicycle parking  
        - label: _(Other)
          value: Other             
      name: bike_issue
      optional: true                                        
    - prompt: _(Please tell us more about the issue at this spot?)
      type: textarea
      name: description_issue
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe the issue at this spot...)                       
    - prompt: _(If possible, please try adding an image of this spot)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/* 
    - prompt: _(What is the main purpose you walk or ride here?)
      type: multi-checkbox
      optional: true
      checkboxes:
        - label: _(Work)
          value: Work
        - label: _(Shopping)
          value: Shopping
        - label: _(School)
          value: School
        - label: _(Exercise)
          value: Exercise
        - label: _(Social)
          value: Social
        - label: _(All purposes)
          value: all                
      name: purpose               
    - prompt: _(How old are you?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(< 14)
          value: '<14'
        - label: _(15-19)
          value: 15-19
        - label: _(20-24)
          value: 20-24
        - label: _(25-34)
          value: 25-34
        - label: _(35-44)
          value: 35-44
        - label: _(45-54)
          value: 45-54
        - label: _(55-64)
          value: 55-64
        - label: _(65-74)
          value: 65-74
        - label: _(>75)
          value: '>75'          
      name: age
      optional: true
    - prompt: _(Your gender)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Male)
          value: male
        - label: _(Female)
          value: female
        - label: _(Other)
          value: other        
      name: gender
      optional: true                                           
    - prompt: _(Your name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Type name)
        - key: size
          value: 30
    - prompt: _(Would you like to stay informed about this project?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Yes - please send updates)
          value: yesplease 
        - label: _(No thanks - no emails please)
          value: nothanks
      name: location_updates
      optional: true           
    - prompt: _(Your email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30      

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
    
  - title: _(FAQs)
    slug: why
    url: /static/pages/why.html
    
  - title: _(Filter âŒ„)
    pages:
      - title: _(Show All)
        url: /
        external: true
      - title: _(Bike Idea Spots)
        url: /filter/bikeidea
        external: true
      - title: _(Walk Idea Spots)
        url: /filter/walkidea
        external: true  
      - title: _(Bike Like Spots)
        url: /filter/bikelike
        external: true
      - title: _(Walk Like Spots)
        url: /filter/walklike
        external: true       
      - title: _(Bike Issue Spots)
        url: /filter/bike
        external: true
      - title: _(Walk Issue Spots)
        url: /filter/walk
        external: true               

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email