# Settings for the app
app:
  # HTML Title
  title: Melbourne Bicycle Plan
  # Header name
  name: Melbourne Bicycle Plan
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to give input on geogrpahic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: -37.814871
      lng: 144.966697
    zoom: 14
    minZoom: 13
    maxZoom: 18
    maxBounds: [ [-37.941876, 144.714997], [-37.739797, 145.087427] ]
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/aisey.lm9h37a2/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  idea:
    index: 0
    label: _(Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FDCB14'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-yellow-idea.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  issue:
    index: 1
    label: _(Issue Spot)
    rules:
      - condition: '"{{location_type}}" === "issue" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "issue" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-red-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "issue" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]                         
  like:
    index: 2
    label: _(Like Spot)
    rules:
      - condition: '"{{location_type}}" === "like" && {{map.zoom}} < 14 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#2AA03C'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "like" && {{map.zoom}} >= 13 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "like" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  offroad:
    index: 3
    label: _(Off-road Shared Path)
    rules:
      - condition: '"{{location_type}}" === "offroad" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "offroad" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/offroad.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "offroad" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  onroad:
    index: 4
    label: _(On-road Bike Lane)
    rules:
      - condition: '"{{location_type}}" === "onroad" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "onroad" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/onroad.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "onroad" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  informal:
    index: 5
    label: _(Informal Bike Route)
    rules:
      - condition: '"{{location_type}}" === "informal" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "informal" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/informal.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "informal" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  bikeparking:
    index: 6
    label: _(Bike Parking)
    rules:
      - condition: '"{{location_type}}" === "bikeparking" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "bikeparking" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/bikeparking.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "bikeparking" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  comlgaboundary:
    index: 7
    label: _(Council Boundary)
    rules:
      - condition: '"{{location_type}}" === "comlgaboundary" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "comlgaboundary" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/comlgaboundary1.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "comlgaboundary" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]                 
                          
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(How can we make cycling in the city better?)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street name/s, Intersection, Landmark, idea etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(An idea)
          value: idea
        - label: _(An issue)
          value: issue
        - label: _(Something I like)
          value: like
      name: location_type
      attrs:
        - key: required        
    - prompt: _(What is the bike issue at this spot?)
      type: select
      options: 
        - label: _(Choose One)
          value: ''
        - label: _(No bicycle lanes)
          value: No bicycle lanes
        - label: _(Unsafe bicycle lanes)
          value: Unsafe bicycle lanes 
        - label: _(Bicycle lane ends unexpectedly)
          value: Bicycle lane ends unexpectedly   
        - label: _(Lack of wayfinding or signage)
          value: Lack of wayfinding or signage  
        - label: _(Bicycle lane blocked)
          value: Bicycle lane blocked
        - label: _(Negative behaviour of other road users)
          value: Negative behaviour of other road users
        - label: _(High risk of car dooring)
          value: High risk of car dooring
        - label: _(Limited or no bicycle parking)
          value: Limited or no bicycle parking  
        - label: _(Other)
          value: Other             
      name: location_bikeissue
      optional: true  
    - prompt: _(Please type 'other' below...)
      type: text
      name: other
      optional: true
      attrs:
        - key: placeholder
          value: _('Other' issue here...) 
    - prompt: _(Does this spot relate to a single location or a section of bicycle route?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Single location)
          value: Single Location
        - label: _(Section of bicycle route)
          value: Route        
      name: location_route
      optional: true                                         
    - prompt: _(Please describe where this section is...)
      type: text
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Eg.from X to X, etc.)
    - prompt: _(Please tell us more about this spot.)
      type: textarea
      name: description_more
      optional: true
      attrs:
        - key: placeholder
          value: _(Eg.more detail about what you like, what the issue is or the idea you would love to see...)
    - prompt: _(If possible, please add an image of this spot)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*         
    - prompt: _(When you think about riding a bike in Melbourne, what one thing would help you to ride more often or start riding?)
      type: textarea
      name: help_ride_more
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe here...)                                                     
    - prompt: _(How old are you?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(< 15)
          value: '<15'
        - label: _(15-19)
          value: 15-19
        - label: _(20-24)
          value: 20-24
        - label: _(25-34)
          value: 25-34
        - label: _(35-44)
          value: 35-44
        - label: _(45-54)
          value: 45-54
        - label: _(55-64)
          value: 55-64
        - label: _(65-74)
          value: 65-74
        - label: _(>75)
          value: '>75'          
      name: age
      optional: true
    - prompt: _(Gender)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Male)
          value: Male
        - label: _(Female)
          value: Female
        - label: _(Other Identity)
          value: Other Identity       
      name: gender
      optional: true
    - prompt: _(Your home postcode)
      type: text
      name: postcode
      optional: true
      attrs:
        - key: placeholder
          value: _(Please type postcode here...)   
    - prompt: _(How do you participate in the City of Melbourne)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Resident)
          value: Resident
        - label: _(Ratepayer)
          value: Ratepayer
        - label: _(Worker)
          value: Worker
        - label: _(Student)
          value: Student 
        - label: _(Visitor)
          value: Visitor  
        - label: _(Business Owner)
          value: Business Owner         
      name: connection
      optional: true                                                   
    - prompt: _(User name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Type name)
        - key: size
          value: 30 
    - prompt: _(Would you like to receive email updates?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Yes)
          value: Yes
        - label: _(No)
          value: No     
      name: optin
      optional: true          
    - prompt: _(Your email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(To receive project updates)
        - key: size
          value: 30      

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: About
    name: overview
    start_page: true
    
  - title: _(FAQs)
    slug: why
    url: /static/pages/why.html
    
  - title: _(Filter âŒ„)
    pages:
      - title: _(Show All)
        url: /
        external: true
      - title: _(Idea Spots)
        url: /filter/idea
        external: true 
      - title: _(Issue Spots)
        url: /filter/issue
        external: true   
      - title: _(Like Spots)
        url: /filter/like
        external: true


notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email