# Settings for the app
app:
  # HTML Title
  title: Melbourne Bicycle Plan
  # Header name
  name: Melbourne Bicycle Plan
  # Meta description that will show up in Google search results
  meta_description: _(CrowdSpot creates custom maps that allow people to give input on geogrpahic locations. Use it to collect data in a social, engaging process.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter the street name and suburb...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: -37.814871
      lng: 144.966697
    zoom: 14
    minZoom: 13
    maxZoom: 18
    maxBounds: [ [-37.941876, 144.714997], [-37.739797, 145.087427] ]
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/aisey.lge52cje/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: /static/data/philadelphia.geojson
      type: json
      rules:
        - condition: 'true'
          style:
            color: "#444"
            opacity: 0.6
            fillOpacity: 0.1
            weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  idea:
    index: 0
    label: _(Idea Spot)
    rules:
      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF039D'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "idea" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-yellow-idea.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "idea" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  issue:
    index: 1
    label: _(Issue Spot)
    rules:
      - condition: '"{{location_type}}" === "like" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "like" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-red-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "like" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]                         
  like:
    index: 2
    label: _(Like Spot)
    rules:
      - condition: '"{{location_type}}" === "like" && {{map.zoom}} < 12 && {{layer.focused}} === false'
        # Display landmarks as circles (vectors) when zoomed out

        style:
          color: '#FF1609'
          radius: 5
          weight: 1
          opacity: 0.9
          fillOpacity: 0.7

      - condition: '"{{location_type}}" === "like" && {{map.zoom}} >= 12 && {{layer.focused}} === false'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/master-pin-green-bike.png
          shadowUrl: /static/css/images/master-pin-shadow.png
          iconSize: [85, 41]
          iconAnchor: [42, 42]

      - condition: '"{{location_type}}" === "like" && {{layer.focused}} === true'
        # Display landmarks as icons when zoomed in

        icon:
          iconUrl: /static/css/images/markers/marker-f95016.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
         
                          
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Add a Spot)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Spots)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(What do you think about bike riding in the City of Melbourne?)
  action_text: _(added)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: location

  items:
    - prompt: _(What is the name of this spot?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Street name/s, Intersection, Landmark, idea etc.)
        - key: size
          value: 30
        - key: required
    - prompt: _(What type of spot is this?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(An idea)
          value: idea
        - label: _(An issue)
          value: issue
        - label: _(Something I like)
          value: like
      name: location_type
      attrs:
        - key: required        
    - prompt: _(What is the bike issue at this spot?)
      type: select
      options: 
        - label: _(Choose One)
          value: ''
        - label: _(No bicycle lanes)
          value: No bicycle lanes
        - label: _(Unsafe or inappropriate bicycle lanes)
          value: Unsafe or inappropriate bicycle lanes 
        - label: _(Bicycle lane ends unexpectedly)
          value: Bicycle lane ends unexpectedly  
        - label: _(Limited or no provision at intersections)
          value: Limited or no provision at intersections  
        - label: _(Lack of wayfinding or signage)
          value: Lack of wayfinding or signage  
        - label: _(Bicycle lane blocked)
          value: Bicycle lane blocked
        - label: _(Negative behaviour of other road users)
          value: Negative behaviour of other road users
        - label: _(High risk of car dooring (narrow/no lane))
          value: High risk of car dooring (narrow/no lane)
        - label: _(Limited or no bicycle parking)
          value: Limited or no bicycle parking  
        - label: _(Other)
          value: Other             
      name: location_bikeissue
      optional: true  
    - prompt: _(If 'other', please type below...)
      type: text
      name: other
      optional: true
      attrs:
        - key: placeholder
          value: _('Other' issue here...) 
    - prompt: _(Does this spot relate to a single location or a section of bicycle route?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Single Location)
          value: Single Location
        - label: _(Section of bicycle route)
          value: Route        
      name: location_route
      optional: true                                         
    - prompt: _(Please describe where this section is..)
      type: text
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Eg.from X to X, etc.)
    - prompt: _(Please tell us more about this spot..)
      type: textarea
      name: description_more
      optional: true
      attrs:
        - key: placeholder
          value: _(Eg.more detail about what you like, what the issue is or the idea you would love to see..)      
    - prompt: _(What goals and targets should a world class cycling city strive for?)
      type: textarea
      name: goals
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe here...) 
    - prompt: _(What key initiatives would help us achieve this?)
      type: textarea
      name: initiatives
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe here...) 
    - prompt: _(What emerging issues should be addressed as part of the draft Bicycle Plan 2016-2020?)
      type: textarea
      name: emerging_issues
      optional: true
      attrs:
        - key: placeholder
          value: _(Please describe here...)                                                
    - prompt: _(If possible, please try adding an image of this spot)
      inputfile_label: _(Add Image)
      type: file
      name: my_image
      optional: true
      attrs:
        - key: accept
          value: image/*          
    - prompt: _(How old are you?)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(< 14)
          value: '<14'
        - label: _(15-19)
          value: 15-19
        - label: _(20-24)
          value: 20-24
        - label: _(25-34)
          value: 25-34
        - label: _(35-44)
          value: 35-44
        - label: _(45-54)
          value: 45-54
        - label: _(55-64)
          value: 55-64
        - label: _(65-74)
          value: 65-74
        - label: _(>75)
          value: '>75'          
      name: age
      optional: true
    - prompt: _(Your home postcode)
      type: text
      name: postcode
      optional: true
      attrs:
        - key: placeholder
          value: _(Please type postcode here...)                                             
    - prompt: _(Your name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Type name)
        - key: size
          value: 30     
    - prompt: _(Your email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30      

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(Welcome)
    slug: welcome
    name: overview
    start_page: true
    
  - title: _(FAQs)
    slug: why
    url: /static/pages/why.html
    
  - title: _(Filter Spots âŒ„)
    pages:
      - title: _(Show All)
        url: /
        external: true
      - title: _(Idea Spots)
        url: /filter/idea
        external: true 
      - title: _(Issue Spots)
        url: /filter/issue
        external: true   
      - title: _(Like Spots)
        url: /filter/like
        external: true


notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email